#!/usr/bin/env python3
"""
build.py: assembles the site's HTML pages.

The nav, <head>, and footer are identical on every page, and keeping five
hand-edited copies in sync is how they drift. This renders them from one
template instead. Page bodies and the widget scripts live in parts/.

All five pages are generated, index.html included. Its layout is unique, so
it passes a few extra slots to head(), but its chrome comes from the same
template as everywhere else. Never hand-edit the generated .html at the root.

Run:  python3 build.py
"""
import io, os

SITE = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(SITE, 'parts')

NAV = [('index.html', 'Home'), ('projects.html', 'Projects'),
       ('lab.html', 'Lab'), ('about.html', 'About')]


def part(name):
    with io.open(os.path.join(PARTS, name), encoding='utf-8') as f:
        return f.read()


def head(page, title, desc, canon, og_desc=None, tw_desc=None,
         doc='', preload='', extra='', body_attr='', body_top=''):
    """Render everything from <!DOCTYPE> down to </header>.

    The optional slots exist only because index.html needs them; every other
    page passes nothing and gets the plain shared chrome.

      og_desc    social-card description. Cards truncate, so the home page
      tw_desc    runs shorter copy than its <meta name="description">.
                 Both default to desc.
      doc        comment block between the doctype and <html>
      preload    extra <link rel="preload">, kept ahead of the font stylesheet
      extra      extra <head> content (inline script, JSON-LD)
      body_attr  attributes on <body>, e.g. ' id="top"'
      body_top   markup between <body> and the nav, e.g. the entry gate
    """
    if og_desc is None:
        og_desc = desc
    if tw_desc is None:
        tw_desc = desc
    nav = '\n'.join(
        '      <a href="%s"%s>%s</a>' % (h, ' class="here"' if h == page else '', l)
        for h, l in NAV)
    return """<!DOCTYPE html>
<!-- Generated by build.py. Do not edit this file; edit parts/ and re-run
     python build.py, or your changes are overwritten on the next build. -->
{doc}<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="https://felixnaroditskiy.com/{canon}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Felix Naroditskiy">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{og_desc}">
<meta property="og:url" content="https://felixnaroditskiy.com/{canon}">
<meta property="og:image" content="https://felixnaroditskiy.com/img/og.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{tw_desc}">
<meta name="twitter:image" content="https://felixnaroditskiy.com/img/og.png">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="alternate icon" href="favicon-32.png" type="image/png" sizes="32x32">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
{preload}<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
{extra}</head>
<body{body_attr}>
{body_top}
<header class="nav">
  <div class="wrap">
    <a class="brand" href="index.html"><i aria-hidden="true"></i>F. NARODITSKIY</a>
    <button class="navtog" id="navtog" aria-expanded="false" aria-controls="pagenav">Menu</button>
    <nav id="pagenav">
{nav}
    </nav>
    <span class="nav-act">
      <a class="solid" href="index.html#top">Contact me</a>
    </span>
  </div>
</header>
""".format(title=title, desc=desc, og_desc=og_desc, tw_desc=tw_desc,
           canon=canon, nav=nav, doc=doc, preload=preload, extra=extra,
           body_attr=body_attr, body_top=body_top)


# Index only. The only [data-resume] trigger on the site is in the home page
# hero, so shipping this to the other pages left dead markup, and an unused
# <iframe>, on four pages that had no way to open it. If a resume link is ever
# added to the shared nav or footer, this has to go back on every page.
RESUME_MODAL = """
<div class="modal" id="resumeModal" role="dialog" aria-modal="true" aria-label="Resume">
  <div class="modal-box">
    <div class="modal-hd">
      <span class="t">Resume &middot; F. Naroditskiy</span>
      <span class="actions">
        <a class="dl" href="NaroditskiyFelixResume.pdf" download>Download</a>
        <a href="NaroditskiyFelixResume.pdf" target="_blank" rel="noopener">Open in tab</a>
        <button id="closeResume">Close</button>
      </span>
    </div>
    <iframe id="resumeFrame" title="Resume" src="about:blank"></iframe>
    <p class="pdf-fallback">Your browser can&rsquo;t preview PDFs inline.<br><a href="NaroditskiyFelixResume.pdf" target="_blank" rel="noopener">Open the resume &rarr;</a></p>
  </div>
</div>
"""


CERT_MODAL = """
<div class="modal" id="certModal" role="dialog" aria-modal="true" aria-label="Certification detail">
  <div class="modal-box cert-box">
    <div class="modal-hd">
      <span class="t" id="certName">Certification</span>
      <span class="actions">
        <a class="dl" id="certVerify" href="#" target="_blank" rel="noopener">Verify</a>
        <button id="closeCert">Close</button>
      </span>
    </div>
    <div class="cert-body" id="certBody"></div>
  </div>
</div>
"""


INDEX_DOC = """<!--
  index.html · Home

  Keep this filename. GitHub Pages serves index.html as the site root, so
  felixnaroditskiy.com/ resolves here. The nav label is what readers see.

  Structure:
    1. Nav          sticky. One action button: Contact me.
    2. Hero         full viewport height. Name, line, portrait, actions.
    3. Facts        four-cell strip, its own band below the hero
    4. Experience   fully open. Stemuli's two roles share one employer block.
    5. Capabilities skills grid + clickable certifications
    6. The work     three cards into Projects, Lab, About
    7. Contact
    8. Modals       resume and certification overlays
    9. Gate         welcome dialog. The markup ships in the page and is shown
                    by CSS the moment the pre-paint head script sets .gating;
                    main.js only wires the behaviour. Once per session.
-->
"""


def footer(next_href, next_label):
    return """
<footer>
  <div class="wrap">
    <span>&copy; 2026 F. Naroditskiy</span>
    <a href="%s">%s &rarr;</a>
  </div>
</footer>
""" % (next_href, next_label)


def write(name, html):
    # newline='\n' keeps the output LF. Without it Python translates to CRLF on
    # Windows, which rewrites every line of every page on each build.
    with io.open(os.path.join(SITE, name), 'w', encoding='utf-8',
                 newline='\n') as f:
        f.write(html)
    print('  %-16s %6d bytes' % (name, len(html.encode('utf-8'))))


def build():
    print('Building pages:')

    # ---- index.html (home) ----
    # The only page with a unique layout, but its nav, <head> and footer are the
    # same shared chrome as everywhere else, so it is built here too. The parts
    # unique to it: a preloaded portrait, the pre-paint gate script and JSON-LD,
    # <body id="top">, the gate markup, and both modals.
    write('index.html',
          head('index.html', 'Felix Naroditskiy · Cybersecurity',
               'Felix Naroditskiy works in digital forensics, malware analysis, and incident response. Ransomware casework, malware triage, hands-on labs, and security governance projects.',
               '',
               og_desc='Digital forensics, malware analysis, and incident response. Ransomware casework, malware triage, and hands-on labs.',
               tw_desc='Digital forensics, malware analysis, and incident response.',
               doc=INDEX_DOC,
               preload='<link rel="preload" as="image" href="img/felix.jpg" imagesrcset="img/felix-sm.jpg 450w, img/felix.jpg 900w" imagesizes="380px">\n',
               extra=part('index_head.html'),
               body_attr=' id="top"',
               body_top='\n' + part('gate.html'))
          + part('index_body.html')
          + RESUME_MODAL
          + CERT_MODAL
          + footer('projects.html', 'Start with the projects')
          + '\n<script src="main.js"></script>\n</body>\n</html>\n')

    # ---- projects.html (casework + archive, merged) ----
    write('projects.html',
          head('projects.html', 'Projects &middot; Felix Naroditskiy',
               'Ransomware kill chain reconstruction, malware analysis casework, IR playbooks, risk analysis, and code.',
               'projects.html')
          + part('projects_body.html')
          + footer('lab.html', 'Next: the lab')
          + part('kc.js.html') + '\n' + part('malware.js.html') + '\n'
          + part('projects.js.html')
          + '\n<script src="main.js"></script>\n</body>\n</html>\n')

    # ---- lab.html ----
    write('lab.html',
          head('lab.html', 'Lab &middot; Felix Naroditskiy',
               'A running log of self-directed security work, laid out as a live alert feed, plus three exercises you can try yourself.',
               'lab.html')
          + part('lab_body.html')
          + footer('about.html', 'Next: about')
          + part('feed.js.html') + '\n' + part('siem.js.html') + '\n'
          + part('pcap.js.html') + '\n' + part('phish.js.html')
          + '\n<script src="main.js"></script>\n</body>\n</html>\n')

    # ---- about.html ----
    write('about.html',
          head('about.html', 'About &middot; Felix Naroditskiy',
               'About Felix Naroditskiy: background, approach, and what I do off the clock.',
               'about.html')
          + part('about_body.html')
          + footer('index.html', 'Get in touch')
          + part('interests.js.html')
          + '\n<script src="main.js"></script>\n</body>\n</html>\n')

    # ---- 404.html ----
    write('404.html',
          head('404.html', '404 &middot; Felix Naroditskiy',
               'Page not found.', '404.html').replace(
              '<link rel="canonical" href="https://felixnaroditskiy.com/404.html">',
              '<meta name="robots" content="noindex">')
          + part('404_body.html')
          + footer('index.html', 'Back to safety')
          + '\n<script src="main.js"></script>\n</body>\n</html>\n')

    print('Done. All five pages are generated; edit parts/, never the HTML.')


if __name__ == '__main__':
    build()
